- name: loop untill playbook
  hosts: all
  tasks: 
    - name: copy
      copy:
        src: "{{item}}"
        dest: ~/
        mode: '0644'
      loop: 
        - program1.sh
        - program2.sh
    - name: run prog1
      shell: 'bash ~/program1.sh'
    - name: wait for log
      find: 
        paths: '~/'
        patterns: 'program1.log'
        recurse: no
        use_regex: yes
      register: findstatus
      until: findstatus.matched == 1
      delay: 2
      retries: 20
    - name: run prog2
      shell: 'bash ~/program2.sh &' 
      register: aa
    - debug:
        msg: "{{aa.stdout}}"