---
- name: condition on user var play
  hosts: all
  vars:
    jdk_pkg: openjdk-14-jdk
  tasks:
    - name: jdk based on env
      set_fact: 
        jdk_pkg: openjdk-11-jdk
      when: env == 'dev'
    - name: print jdk package
      debug: 
        msg: "{{jdk_pkg}}"
...