---
- name: tomcat playbook
  hosts: all
  vars: 
    tomcat_url: 'https://dlcdn.apache.org/tomcat/tomcat-10/v10.0.23/bin/apache-tomcat-10.0.23.tar.gz'
  tasks:
    - name: install jdk 11
      apt:
        name: openjdk-11-jdk
        state: present
        update_cache: yes
      become: yes
    # - name: download tomcat 10
    #   get_url:
    #     url: "{{tomcat_url}}"
    #     dest: ~/
    #     mode: 0755
    # - name: extract tomcat
    #   unarchive:
    #     src: ~/apache-tomcat-10.0.23.tar.gz
    #     dest: ~/
    #     remote_src: true
    - name: start tomcat
      shell: /home/vagrant/apache-tomcat-10.0.23/bin/catalina.sh run 2>&1 | grep "java.net.BindException"
      become: yes
      register: status
      changed_when: "'Address already in use' not in status.stdout"
    - name: print
      debug:
        msg: "{{status}}"   
...