- name: simple loop
  hosts: all
  tasks:
    - name: install all packages
      apt:
        name: "{{item}}"
        update_cache: yes
        state: present
      become: yes
      loop:
        - tree
        - vim
        - net-tools