- name: tomcat service file
  template:
    src: tomcat.service.j2
    dest: /etc/systemd/system/tomcat.service
  become: yes
- name: start
  service: 
    name: tomcat
    state: restarted
  become: yes