- name: create tomcat user
  user:
    name: "{{tomcat_os_user}}"
    create_home: yes
    state: present

  become: yes

- name: create tomcat install directory
  file:
    path: "{{tomcat_install_dir}}"
    state: directory
    owner: "{{tomcat_os_user}}"
    group: "{{tomcat_os_user}}"
    mode: '0755'
  become: yes
- name: create tomcat dir
  file: 
    path: "{{tomcat_install_dir}}/{{tomcat_dir}}"
    state: directory
    owner: "{{tomcat_os_user}}"
    group: "{{tomcat_os_user}}"
    mode: '0755'
  become: yes