- name: service playbook
  hosts: ab
  tasks: 
    # - name: install apache2
    #   apt: 
    #     name: apache2
    #     state: present
    #     update_cache: yes
    #     autoclean: yes
    #     autoremove: yes
    #   become: yes
    - name: start apache2
      service:
        name: apache2
        state: started
      become: yes
